### PR TITLE
crc: implement table-driven crc algorithm

### PR DESCRIPTION
**Pull request by zhiyuan-zhu**
Change-Id: Iebfb8ae1db09bf2dc882fd87e61627d74fab4a5c
Signed-off-by: Zhiyuan Zhu <zhiyuan.zhu@arm.com>

Hi, for crc16/crc32/crc64 table-driven version implementation

### CODE REVIEW

**Comment by gbtucker** [comment]
Table-based versions would be a good replacement for the base functions that don't currently use them.  No need to add additional exported functions that perform the same operation.  Instead replace the slower base functions and move the simple but slow version to be the reference functions only called by the tests.

**Comment by zhiyuan-zhu** [comment]
Hi @gbtucker,

Thanks for your kindly reply, the changes briefly as follows,

crc_base.c and crc64_base.c now contains table-based code, 
original crc_base.c and crc64_base.c is renamed to crc_ref.c and crc64_ref.c,
So, the base functions will call the table-based version functions.

**Comment by zhiyuan-zhu** [comment]
@gbtucker, thanks for your suggestions, the revised summary is as follows,

1. Move the reference functions to .h file, and inline them
2. Rename some functions name: crc*_base_ref => crc*_ref
3. Only test module include the files: 
    crc/crc_ref.h and crc/crc64_ref.h
4. For test case, only one entry point for each function

**Comment by zhiyuan-zhu** [comment]
Sorry for have a mis-operation

**Pull request closed without merging**
