### PR TITLE
fixing huff_codes.c's compiling problem on CentOS 6.5 as gcc 4.4.7 on…

### PR DESCRIPTION
**Pull request by iamhumanbeing**
fixing huff_codes.c's compiling problem on CentOS 6.5 as gcc 4.4.7 only support C89

[xp@perf-slave1 isa-l]$  gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[xp@perf-slave1 isa-l]$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.5 (Santiago)
Release:	6.5
Codename:	Santiago

  CC     igzip/encode_df.lo
  CC     igzip/huff_codes.lo
igzip/huff_codes.c:61: error: unknown field ‘code_and_extra’ specified in initializer
igzip/huff_codes.c:61: warning: missing braces around initializer
igzip/huff_codes.c:61: warning: (near initialization for ‘static_hufftables.lit_len_table[0].<anonymous>’)
igzip/huff_codes.c:61: error: unknown field ‘length2’ specified in initializer
igzip/huff_codes.c:61: warning: excess elements in struct initializer
igzip/huff_codes.c:61: warning: (near initialization for ‘static_hufftables.lit_len_table[0]’)
igzip/huff_codes.c:62: error: unknown field ‘code_and_extra’ specified in initializer
igzip/huff_codes.c:62: error: unknown field ‘length2’ specified in initializer
igzip/huff_codes.c:62: warning: excess elements in struct initializer
igzip/huff_codes.c:62: warning: (near initialization for ‘static_hufftables.lit_len_table[1]’)
igzip/huff_codes.c:63: error: unknown field ‘code_and_extra’ specified in initializer
igzip/huff_codes.c:63: error: unknown field ‘length2’ specified in initializer
igzip/huff_codes.c:63: warning: excess elements in struct initializer
igzip/huff_codes.c:63: warning: (near initialization for ‘static_hufftables.lit_len_table[2]’)
igzip/huff_codes.c:64: error: unknown field ‘code_and_extra’ specified in initializer
igzip/huff_codes.c:64: error: unknown field ‘length2’ specified in initializer
igzip/huff_codes.c:64: warning: excess elements in struct initializer
igzip/huff_codes.c:64: warning: (near initialization for ‘static_hufftables.lit_len_table[3]’)

### CODE REVIEW

**Comment by gbtucker** [comment]
Thanks for testing and the fix.  I'll run on a few more machines and see if there are any issues.

**Comment by iamhumanbeing** [comment]
If there are any issues, pls let me know

**Comment by gbtucker** [comment]
Looks good.  Can I ask that you amend with signoff (-s) as described in [contributing](https://github.com/01org/isa-l/blob/master/CONTRIBUTING.md)?

**Comment by iamhumanbeing** [comment]
yes, I have amend with signoff. pls check it.
If it does't work, pls let me konw how to make it. 
I just run command "git commit --signoff -a -m "for signoff" "

**Comment by gbtucker** [comment]
I'm getting a formatting error.  Sorry, my fault for not checking in format checker.  To amend previous patch should be something like
  `git reset --hard 39a8b266`  // to cut out last commit
  `git commit -a -s --amend`  // to just add sign-off to previous commit
  `git push -f origin HEAD` // this may vary
If it doesn't work for you I can squash on my end and fix the formatting error.

**Comment by iamhumanbeing** [comment]
@gbtucker Thanks for your reply.
I have run the 4 git commands on my PC. 
is it OK now?

**Comment by gbtucker** [comment]
Perfect, thanks.

**Comment by iamhumanbeing** [comment]
@gbtucker : sorry for no reply for your email because company policy.

**Pull request merged**
